# -*- coding: utf-8 -*-
"""Amazon_sale_EDA_pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jq8YxAdh0DW8tx9BUCuTkYywm8T-FGaZ
"""

# ================================
# STEP 1: IMPORTING DATA
# ================================

# Uploading CSV file from local system (Google Colab specific)
from google.colab import files
uploaded = files.upload()

# Importing required libraries
import pandas as pd      # For data analysis and manipulation
import numpy as np       # For numerical operations

# Reading the dataset
df = pd.read_csv("Amazon_sale_1000Rows.csv")

# ================================
# STEP 2: DATA SAFETY & BASIC CLEANING
# ================================

# Creating a deep copy of the original dataframe
# So that changes do not affect the raw dataset
df1 = df.copy().drop(columns=["index", "promotion-ids"])

# Previewing the data
df1.head()
df1.tail()

# ================================
# STEP 3: DATA TYPE CORRECTIONS
# ================================

# Converting Date column to datetime format
# This enables time-based analysis if needed later
df1["Date"] = pd.to_datetime(df1["Date"])

# ================================
# STEP 4: HANDLING MISSING VALUES
# ================================

# Checking missing values in each column
df1.isnull().sum()

# Dropping rows where Amount is missing
# Amount is a revenue column, so missing values cannot be used for analysis
df1.dropna(subset=["Amount"], inplace=True)

# ================================
# STEP 5: STANDARDIZING COLUMN NAMES
# ================================

# Replacing hyphens with underscores for cleaner column naming
df1.columns = df1.columns.str.replace("-", "_")

df1.columns

# ================================
# STEP 6: STATUS LEVEL ANALYSIS
# ================================

# Understanding order distribution by fulfilment status
df1["fulfilled_by"].value_counts()

# Aggregated analysis by Status
# This helps in understanding revenue realization vs risk
df1.groupby("Status").agg(
    total_amount=("Amount", "sum"),
    total_qty=("Qty", "sum"),
    total_orders=("Order ID", "count")
)

# ================================
# STEP 7: REVENUE SEGMENTATION
# ================================

# Defining business rules for revenue classification
# This helps separate realized, at-risk, and lost revenue
status_to_bucket = {
    "Shipped - Delivered to Buyer": "Realized",
    "Shipped": "At Risk",
    "Cancelled": "Lost",
    "Shipped - Returned to Seller": "Lost",
    "Shipped - Rejected by Buyer": "Lost"
}

# Mapping revenue buckets to each order
df1["Revenue_bucket"] = df1["Status"].map(status_to_bucket)

# Checking distribution of revenue buckets
df1["Revenue_bucket"].value_counts()

# ================================
# STEP 8: FULFILMENT ANALYSIS
# ================================

# Checking missing values in Fulfilment column
df1["Fulfilment"].isnull().sum()

# Distribution of orders by fulfilment type
df1["Fulfilment"].value_counts()

# Cross-tab between Fulfilment type and Revenue Bucket
# Helps understand how fulfilment impacts revenue realization
pd.crosstab(df1["Fulfilment"], df1["Revenue_bucket"])

# ================================
# STEP 9: MERCHANT-LEVEL DEEP DIVE
# ================================

# Filtering only Merchant fulfilled orders
merchant_df = df1[df1["Fulfilment"] == "Merchant"]

# Cross-tab to analyze Easy Ship impact on revenue outcome
pd.crosstab(merchant_df["fulfilled_by"], merchant_df["Revenue_bucket"])

# ================================
# STEP 10: FINAL OBSERVATIONS
# ================================

# Checking overall fulfilment method distribution
df1["fulfilled_by"].value_counts()

# Checking the overall distribution of revenue buckets
# This helps understand how many orders are realized, at risk, or lost
df1["Revenue_bucket"].value_counts(normalize=True) * 100


# Filtering only the 'At Risk' orders
# These are shipped but not yet delivered and represent potential revenue
At_risk_df1 = df1[df1["Revenue_bucket"] == "At Risk"]


# Inspecting the Amount column for at-risk orders
# This gives an idea of order value spread before bucketing
At_risk_df1["Amount"]


# Creating value-based buckets for at-risk orders
# The goal is to understand whether risk is coming from low-value or high-value orders
At_risk_df1["Value_buckets"] = pd.cut(
    At_risk_df1["Amount"],
    bins=[0, 500, 1000, 2000, 2500, np.inf],
    labels=["Very Low", "Low", "Medium", "High", "Very high"]
)


# Previewing the dataframe after adding value buckets
At_risk_df1


# Checking the percentage distribution of at-risk orders across value buckets
# This helps prioritize which orders need manual attention vs automation
At_risk_df1["Value_buckets"].value_counts(normalize=True) * 100

# Understanding the overall revenue distribution across different order outcomes
# This gives a high-level view of realized vs at-risk vs lost revenue
df1["Revenue_bucket"].value_counts(normalize=True) * 100


# Creating a separate dataframe for at-risk orders
# These are shipped orders that still have the potential to convert into revenue
At_risk_df1 = df1[df1["Revenue_bucket"] == "At Risk"]


# Reviewing order amounts for at-risk orders
# Helps understand the value spread before segmentation
At_risk_df1["Amount"]


# Segmenting at-risk orders into value buckets
# This allows prioritization based on potential revenue impact
At_risk_df1["Value_buckets"] = pd.cut(
    At_risk_df1["Amount"],
    bins=[0, 500, 1000, 2000, 2500, np.inf],
    labels=["Very Low", "Low", "Medium", "High", "Very high"]
)


# Quick check to ensure value buckets are assigned correctly
At_risk_df1


# Checking how at-risk orders are distributed across value buckets (in percentage terms)
# This highlights whether risk is volume-driven or value-driven
At_risk_df1["Value_buckets"].value_counts(normalize=True) * 100


# Rechecking the full dataset (sanity check before deeper segmentation)
df1


# Comparing B2B vs B2C behavior within at-risk orders
# Helps understand whether revenue risk is coming from business or consumer orders
pd.crosstab(
    At_risk_df1["B2B"],
    At_risk_df1["Value_buckets"],
    normalize="index"
) * 100


# Focusing only on B2C at-risk orders for further analysis
# B2C typically contributes higher order volume and revenue variability
b2c_at_risk = At_risk_df1[At_risk_df1["B2B"] == False]


# Previewing B2C at-risk data before category-level analysis
b2c_at_risk


# Category-wise value distribution for B2C at-risk orders
# Helps identify which product categories contribute to meaningful revenue risk
pd.crosstab(
    b2c_at_risk["Category"],
    b2c_at_risk["Value_buckets"],
    normalize=True
) * 100


# Creating a focused dataset of high-priority at-risk orders
# These are B2C orders in the 'Set' category with medium to high order value
priority_risk_df = At_risk_df1[
    (At_risk_df1["B2B"] == False) &
    (At_risk_df1["Category"] == "Set") &
    (At_risk_df1["Value_buckets"].isin(["Medium", "High"]))
]


# Viewing key details of priority orders
# This table represents actionable items for operations or fulfilment teams
priority_risk_df[["Order ID", "Category", "Amount", "Fulfilment", "fulfilled_by"]].head()


